### ISSUE TITLE
Can I please update angular and make it ionic

### ISSUE THREAD

**Issue by wbhob** [srnd/Companion.Web#6]
Angular 1 sucks. Long live Angular (5?)

It's maintainable.
It's fast.
And I want to make it eventually if I have time.

Let me know if this is something you want.

**Comment by tjhorner** [comment]
Maybe later. But not now. We're working on the native Android version, so I want to finish that first before we make any changes here.

**Comment by tylermenezes** [comment]
Everyone has an opinion on programming languages; if we re-wrote projects per everyone's preferences we would be rewriting literally forever.

**Comment by wbhob** [comment]
Valid, I'm just saying that AngularJS will soon be deprecated, and Angular will be receiving periodic improvements to bundle size and performance.

**Comment by tjhorner** [comment]
Ok, but it still works perfectly fine for our needs. Unless there is a HIGHLY significant performance increase, or some really critical security issue (which can be patched), I don't plan on switching. I am familiar with AngularJS, and I don't feel like learning yet another framework at the moment.
